/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deocades.erpilua;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author Rajah Joevil
 */
public class ViewReservations extends javax.swing.JFrame {

    /**
     * Creates new form ShowReservations
     */
    public ViewReservations() {
        initComponents();
        Display.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Display = new javax.swing.JTextPane();
        Return = new javax.swing.JButton();
        DeleteReserv = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Poor Richard", 1, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Show Reservations");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");

        Display.setEditable(false);
        Display.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        Display.setForeground(new java.awt.Color(255, 255, 255));
        Display.setText("hytnhtnrhtfnh\nwrvtsebysy\nybserbystybser\nybesys\nysyb\nyrybe\nybe5t5ybrtun\nrtyhertudr\nybrtu\n");
        jScrollPane1.setViewportView(Display);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 420, 150));

        Return.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        Return.setText("Return");
        Return.setBorder(null);
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        jPanel1.add(Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 120, 40));

        DeleteReserv.setFont(new java.awt.Font("Poor Richard", 0, 24)); // NOI18N
        DeleteReserv.setText("Delete Reservation");
        DeleteReserv.setBorder(null);
        DeleteReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteReservActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteReserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 180, 40));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deocades/erpilua/SBG.jpeg"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained

    }//GEN-LAST:event_jPanel1FocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        try {
            FileReader FR = new FileReader("LogBook.txt");
            BufferedReader BR = new BufferedReader(FR);
            String message = "";

            int CharNum = BR.read();

            while (CharNum != -1) {
                char location = (char) CharNum;
                message = message + location;
                Display.setText(message);
                CharNum = BR.read();
            }

        } catch (IOException e) {
            System.out.println("File not found :-:");
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:
        Main ReturnWin = new Main();
        ReturnWin.show();
        dispose();
    }//GEN-LAST:event_ReturnActionPerformed

    private void DeleteReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteReservActionPerformed
        // TODO add your handling code here:
        DeleteReservation GoDelete = new DeleteReservation();
        GoDelete.show();
        dispose();
    }//GEN-LAST:event_DeleteReservActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReservations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton DeleteReserv;
    private javax.swing.JTextPane Display;
    private javax.swing.JButton Return;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
